version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: ims_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ims_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: ims_redis
    ports:
      - "6379:6379"